name = "open-user-state-personal-website"
main = "src/index.ts"
compatibility_date = "2024-05-25"
node_compat = true
kv_namespaces = [
  { binding = "USER_PAT_STORE", id = "8b99c8c064fc4eadb803d6018f4516b9", preview_id = "8b99c8c064fc4eadb803d6018f4516b9" }
]
