name = "open-user-state-personal-website"   # production script
main = "src/index.ts"
compatibility_date = "2024-05-25"
node_compat = true
workers_dev = true        # prod will have workers.dev URL

[observability.logs]
enabled = true

####################################
# Production (root) – vars & KVs
####################################
# (If you prefer, you can move these into [env.production] instead; then remove from root.)

[[kv_namespaces]]
binding    = "USER_PAT_STORE"
id         = "8b99c8c064fc4eadb803d6018f4516b9"

[[kv_namespaces]]
binding    = "USER_REPO_STORE"
id         = "3ba5ec05252d481388ab12ef71d28f56"

[[kv_namespaces]]
binding    = "SESSIONS"
id         = "bb9d2ee7778841588128d1b9367def84"

# (Root vars for production)
[vars]
RUNTIME_ENV        = "production"
FRONTEND_ORIGIN    = "https://viktor-shcherb.github.io"
GITHUB_CLIENT_ID   = "Ov23liFRU2GYxAyhNmTb"
GITHUB_REDIRECT_URI = "https://open-user-state-personal-website.viktoroo-sch.workers.dev/api/auth/github/callback"

####################################
# Development environment
####################################
[env.dev]
name = "open-user-state-personal-website-dev"
workers_dev = true       # dev workers.dev URL enabled

[[env.dev.kv_namespaces]]
binding = "USER_PAT_STORE"
id      = "218c3796d9ca45028bd1ad7f388cca54"

[[env.dev.kv_namespaces]]
binding = "USER_REPO_STORE"
id      = "00510ebb501e44bbb50a96f223807f51"

[[env.dev.kv_namespaces]]
binding = "SESSIONS"
id      = "94045e87f8c44af2b237345d4c02ee46"

[env.dev.vars]
RUNTIME_ENV        = "dev"
FRONTEND_ORIGIN    = "http://localhost:4000"
GITHUB_CLIENT_ID   = "Ov23liBELtLNvMl3UBWN"
GITHUB_REDIRECT_URI = "https://open-user-state-personal-website-dev.viktoroo-sch.workers.dev/api/auth/github/callback"
