# .github/workflows/deploy.yml
name: Deploy Worker

on:
  push:
    branches: [ dev, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: worker-deploy-${{ github.ref_name }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Deploy (select env)
        uses: cloudflare/wrangler-action@v3
        with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
            accountId: ${{ secrets.CF_ACCOUNT_ID }}
            command: |
              if [ "${{ github.ref_name }}" = "dev" ]; then
                echo "Deploying DEV environment"
                wrangler deploy --env dev
              else
                echo "Deploying PRODUCTION environment"
                wrangler deploy --env production
              fi
