name: Deploy Worker
on:
  push:
    branches: [ dev, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler (pin a version)
        run: npm install --no-save wrangler@4

      - name: Deploy (branch-based)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "Branch: $GITHUB_REF_NAME"
          if [ "$GITHUB_REF_NAME" = "dev" ]; then
            echo "Deploying DEV"
            npx wrangler deploy --env dev
          elif [ "$GITHUB_REF_NAME" = "master" ]; then
            echo "Deploying PRODUCTION"
            npx wrangler deploy --env production
          else
            echo "No deploy rule for branch $GITHUB_REF_NAME"
            exit 0
          fi
